from __future__ import annotations

import json

import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from verifysignal_spec.runtime.release_signature import (
    PRODUCTION_RELEASE_PUBLIC_KEYS,
    TEST_RELEASE_KEY_ID,
    _load_public_key,
    trusted_release_keys,
)

# RATCHET (production release trust anchor, 2026-07-24 cutover). A clean machine — no env vars, no
# test flags — must trust exactly the production release-signing key, or the managed install path
# only works on machines that were hand-configured. The PEM is pinned byte-for-byte against the
# public half generated by scripts/runtime/generate-release-keypair.ts (Core repo) and mirrored in
# the BE deploy env; a drifted or corrupted constant must fail here, not at install time.

PRODUCTION_KEY_ID = "verifysignal-core-release-2026"
EXPECTED_PEM = (
    "-----BEGIN PUBLIC KEY-----\n"
    "MCowBQYDK2VwAyEAkplu04rmKl1GFpr+e1UdhIcsPlI1qVbYnQjBWBSH7ow=\n"
    "-----END PUBLIC KEY-----"
)


def test_clean_machine_trusts_exactly_the_production_key(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("VERIFYSIGNAL_RUNTIME_RELEASE_PUBLIC_KEYS", raising=False)
    monkeypatch.delenv("VERIFYSIGNAL_ALLOW_TEST_RELEASE_KEYS", raising=False)

    keys = trusted_release_keys()

    assert keys.get(PRODUCTION_KEY_ID, "").strip() == EXPECTED_PEM
    # The test key must never ride along implicitly.
    assert TEST_RELEASE_KEY_ID not in keys
    assert set(keys) == {PRODUCTION_KEY_ID}


def test_embedded_constant_is_a_loadable_ed25519_key() -> None:
    assert set(PRODUCTION_RELEASE_PUBLIC_KEYS) == {PRODUCTION_KEY_ID}
    key = _load_public_key(PRODUCTION_RELEASE_PUBLIC_KEYS[PRODUCTION_KEY_ID])
    assert isinstance(key, Ed25519PublicKey)


def test_env_configuration_adds_but_cannot_remove_the_anchor(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv(
        "VERIFYSIGNAL_RUNTIME_RELEASE_PUBLIC_KEYS",
        json.dumps({"extra-key": "-----BEGIN PUBLIC KEY-----\nAAAA\n-----END PUBLIC KEY-----"}),
    )
    monkeypatch.delenv("VERIFYSIGNAL_ALLOW_TEST_RELEASE_KEYS", raising=False)

    keys = trusted_release_keys()

    assert PRODUCTION_KEY_ID in keys
    assert "extra-key" in keys
